### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by trevinhofmann** [irislib/iris-messenger#108]
Would you be interested in having this project set up to use TypeScript instead of JavaScript? In my experience, TS naturally helps with code readability and bug prevention.

**Comment by mmalmi** [comment]
Yes, typescript would be great. I've been coding in rust lately, which has very concretely shown the benefits of strong typing.

**Comment by worldpeaceenginelabs** [comment]
Hey Guys, you just speak from my soul 🙏

I just started a fork of Iris https://github.com/worldpeaceenginelabs/METAVERSE-GUN

![image](https://user-images.githubusercontent.com/67427045/173733545-df58dcef-41fa-430f-978f-c3b893226a9d.png)


Iris Messenger is just such a good base to start something like this. Look at all the green checkboxes in readme.md (this is what the iris-community has already accomplished) 🙏 just wow! 🤯

I would love to have the codebase of Iris in Svelte!

Since Svelte isnt a language but a clean JS compiler, its like writing in react or vue for instance, but saving the framework typical boilerplate. (You dont need to learn anything new) Like i transfered js code from react projects to Svelte with just cutting off the uneccasary bs surrounding the actual code 😅

Svelte does even safe you the DOM/router stuff. So its basically connecting components via imports, exports and modals only.
Less code, better readability, less bugs, less space, faster execution!

This video hitted me. So simple. And since it is clean, typed js, its easier to reuse code or get a snippet from stackexchange.
https://youtu.be/J5x3OMXjgMc Gun Svelte Chat App

Iris definitly needs a makeover to get more code contributions.

If not Svelte, then minimum Typescript and markup seperated from JS.
Oh what a coincidence, the last part was just Svelte i described 😅
