### ISSUE TITLE
clarify message deletion behavior in user docs

### ISSUE THREAD

**Issue by khimaros** [irislib/iris-messenger#159]
when a user deletes a public message, is it removed from all peers in the canonical implementation?

is this done via append-only (eg. tombstoning) or actual deletion?

are mutations/edits supported and propagated as well?

**Comment by mmalmi** [comment]
When you "delete" a post, it actually just deletes a link to the post from your list of posts. True, this could be documented somewhere.

Posts themselves are stored by hash (`gun.get('#').get(msgHash).put(msg)`) and not removed. Storing the posts by hash is necessary so that something you liked or replied to can't be changed afterwards, and if you "retweet" something, you don't need to duplicate the same 3 MB image file for example.

**Comment by khimaros** [comment]
@mmalmi what would happen if you were to take an existing message hash `gun.get('#').get(msgHash).put(null)`,

the GUN documentation seems to indicate that this is possible: https://gun.eco/docs/Delete

am i missing some other constraint?

**Comment by khimaros** [comment]
am i misinterpreting this code? https://github.com/irislib/iris-messenger/blob/aaa421c92bfdd2c97f69fc8358cd27a934dd0a05/src/js/components/PublicMessage.js#L176

it sort of looks like the behavior i'm asking for is actually already implemented there. @mmalmi could you confirm?

**Comment by mmalmi** [comment]
`gun.get('#').get(hash).put(value)` only works when `value` matches the hash, so `null` is not saved.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
