### ISSUE TITLE
In order to build a security critical messenger app

### ISSUE THREAD

**Issue by marcoippolito** [irislib/iris-messenger#25]
Hi!
In https://github.com/irislib/iris-messenger#privacy
I read "Messages are end-to-end encrypted, but message timestamps and the number of chats aren't. In a decentralized network this information is potentially available to anyone.

By looking at timestamps in chats, it is possible to guess who are chatting with each other. It is also possible, if not trivial, to find out who are communicating with each other by monitoring data subscriptions on the decentralized database.

In that regard, Iris prioritizes decentralization and availability over perfect privacy.

Profile names, photos and online status are currently public. That can be changed when advanced group permissions are developed.

The application is an unaudited proof-of-concept implementation, so don't use it for security critical purposes."

In case I would use iris-messenger as starting point for building a messenger app for security critical purposes, probably the starting points would be to encrypt the message timestamps and encrypt the number of chats.
But how hide the data subscriptions on the decentralized database?
Which other aspects for security should I consider?
How would you suggest me to proceed?

Looking forward to your kind suggestions and hints.
Marco

**Comment by mmalmi** [comment]
The thing is, message timestamps cannot be encrypted because they are used to query messages from peers ordered by time. We could index messages by *day only* instead of full timestamp to obfuscate it a bit, but still be able to return them kind-of ordered by date.

As for other security improvements: if I knew, I would implement them 🙂 We will be improving security as we go.

**Comment by marcoippolito** [comment]
Thank you for your kind response
