### ISSUE TITLE
receiving data is so slow

### ISSUE THREAD

**Issue by isbincApps** [irislib/iris-messenger#29]
hi, amazing job. Why receiving data is so slow

**Comment by pwFoo** [comment]
Post a comment is really slow and also locally is shown with much delay!
Maybe it should be added as preview with a indicator to be saved / loaded remote to get the ui smooth?

Each port user await response should show a loading indicator because user should now something is happen in the background?

**Comment by mmalmi** [comment]
It's a Gun issue https://github.com/amark/gun/issues/1068

**Comment by pwFoo** [comment]
Thanks! I subscribed the issue

**Comment by petrikaj** [comment]
Iris is a nostr client now.
